ALTER TABLE Clientes 
MODIFY Nombre VARCHAR(100) NOT NULL,
MODIFY Email VARCHAR(100) NOT NULL,
MODIFY Fecha_Registro DATE NOT NULL
;

ALTER TABLE Vendedores 
MODIFY Nombres VARCHAR(100) NOT NULL
;

ALTER TABLE Telefonos_Vendedores 
MODIFY Numero_Telefono VARCHAR(100) NOT NULL
;

ALTER TABLE FechasTrabajo_Vendedores
MODIFY ID_Vendedor INT NOT NULL,
MODIFY FechaInicio DATE NOT NULL,
MODIFY FechaFin DATE NOT NULL
